---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-alpine

inputs:
- name: repo
- name: out

outputs:
- name: out

run:
  path: git-repo/ci/tasks/copy.sh
