---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk

inputs:
  - name: tools
  - name: version
  - name: from-repo
  - name: to-repo
  - name: m2

outputs:
  - name: out

run:
  path: repo/ci/tasks/bump-version/task.sh

params:
  GIT_EMAIL:
  GIT_NAME:
