---
resource_types:
  - name: artifactory-resource
    type: docker-image
    source:
      repository: springio/artifactory-resource
      tag: 0.0.1-SNAPSHOT

resources:
- name: git-repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    private_key: ((github-private-key))

- name: artifactory
  type: artifactory-resource
  source:
    uri: ((artifactory-url))
    username: ((artifactory-username))
    password: ((artifactory-password))
    build_name: test-build

jobs:
## develop pipeline
- name: build
  plan:
    - get: git-repo
      trigger: true
    - task: build
      file: git-repo/ci/tasks/build.yml
    - put: artifactory
      params:
        repo: libs-snapshot-local
        build_number: ${BUILD_ID}
        folder: test
        build_url: https://wings.concourse.ci/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}
- name: test
  plan:
    - get: artifactory
      trigger: true
      passed: [build]
